### ISSUE TITLE
Some TVs show mobile view 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#180]
Please add the query string ?view=desktop at the end of the mosque url
Example https://mawaqit.net/en/id/1847?view=desktop

some tvs send a mobile user-agent so the server redirects them to the mobile view

**Comment by omar-cherif** [comment]
@ismaelAbogabal could you please test the official release on different boxes and confirm the results?

We need to make sure that this behaviour is no longer reproductible on different box models.

Thanks

**Comment by ismaelAbogabal** [comment]
Testing on these devices 
download the app from google play 
Google Play install the right build version type(android version)

## Test devices
- X96 MAX with (cortex-A53 processor) android 9 
- Mi box s 
- Mi stick 
- Chromecast 4th generation 
- Tevii p500 (cortex-A53 processor)

**Comment by omar-cherif** [comment]
Excellent !
Thank you very much for your kind confirmation!

**Comment by omar-cherif** [comment]
@ismaelAbogabal 
Issue is still present. 
The mobile version is installed instead of the TV version on many Android boxes. (Especially those that do not use the Leanback launcher, and do use a custom launcher.

So, let's think again about an Androidmanifest restriction besides the Leanback launcher, as many android box manufacturers do have a custom ROM and a custom Launcher.

**Comment by omar-cherif** [comment]
Same behavior (Mobile app installed instead of TV) on T95Z box (Android 12.0) with a custom launcher.

Android 12.0 TV Box T95Z Plus Android Box 4 Go RAM 32 Go ROM Allwinner H618 Quad Core 64 bits Support HD 6K / 3D / H.265 Ethernet 2.4/5G Dual WiFi BT 5.0
https://www.amazon.fr/Android-Allwinner-Support-H-265-Ethernet/dp/B08SW8DQT1/

**Comment by omar-cherif** [comment]
Same behavior (Mobile app installed instead of TV) on X96 box (Android 11.0) with a custom launcher.

X96 X4 Android 11.0 TV Box 4 Go RAM 64 Go Amlogic S905X4 Quad Core A55 Dual WiFi 2,4 G/5G Airplay Miracast VP9 H.265 Bluetooth Smart TV Box
https://www.amazon.fr/gp/product/B09GRS6QLZ/

**Comment by ismaelAbogabal** [comment]
> android.software.leanback 

is the only feature that distinguishes TVs  from android phones
From my perspective To solve we have two options 
1- Using screen-based restriction. 
2- Having two separate apps on google play 
3- Building the web view inside the mobile application 

### screen-based restriction 
Will be done in a few time. but can't recommend it because it regards tabled as a TV 

### Building web view inside the mobile application 
As our main goal is to support offline mode inside android TV.
Building it into the android app will help a lot in that

We give the tablets two options to use the app 
- android view 
- Tv view

**Comment by omar-cherif** [comment]
@ismaelAbogabal Here's the list of the certified android boxes by Google
https://docs.google.com/spreadsheets/d/1kdnHLt673EjoAJisOal2uIpcmVS2Defbgk1ntWRLY3E/

**Comment by omar-cherif** [comment]
Another list:
https://docs.google.com/spreadsheets/d/1WPX-WJISk6l-5P85goa4_QfkDXn9us8GI649GxKDSgI/edit#gid=0

**Comment by ismaelAbogabal** [comment]
after researching in 
[android user-feature docs](https://developer.android.com/guide/topics/manifest/uses-feature-element)
i found out that adding these lines should solve the issue 
```XML
<uses-feature android:name="android.hardware.touchscreen" android:required="true" />
```

**Comment by omar-cherif** [comment]
@ismaelAbogabal The touchscreen requirement present in the Mobile App Manifest.

![Screenshot_2022-09-25-16-05-32-55_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/33727630/192147898-83b56c55-d52f-4fd2-b1eb-aadc0531c636.jpg)

**Comment by omar-cherif** [comment]
@ibrahim-zehhaf-mawaqit here's the issue (we can put here the differents test results to keep track).

**Comment by omar-cherif** [comment]
Issue Closed.
We do require Leanback for Android TVs

(TVs and Boxes that does not have Leanback will have to manually install the MAWAQIT Apk's (Launcher + App).
