### ISSUE TITLE
add background if color or motif

### ISSUE THREAD

**Issue by AnasElbattra** [mawaqit/android-tv-app#308]
![Screenshot (296)](https://user-images.githubusercontent.com/75434006/211985698-3a21aac1-5c50-4e66-ab4d-e6fb85c16a4b.png)

**Comment by AnasElbattra** [comment]
@ibrahim-zehhaf-mawaqit  How can I get an image from code in case Motif

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> @ibrahim-zehhaf-mawaqit How can I get an image from code in case Motif

You can find the background motif here `backgroundMotif` in the api `/config`
as mentioned in the swagger here http://swagger.mawaqit.net:83/#/default/get_mosque__uuid__config
backgroundMotif is The code number of the background picture

Here is the pattern to get the picture 

If backgroundMotif = 0 then get the picture from /info > interiorPicture (coming soon in https://github.com/mawaqit/backend/issues/252)
If backgroundMotif = 1 then get the picture from /info > exteriorPicture (coming soon in https://github.com/mawaqit/backend/issues/252)
Otherwise use this url 
https://mawaqit.net/bundles/app/prayer-times/img/background/[backgroundMotif].jpg
