### ISSUE TITLE
Iqama = 0 is not working correctly, the countdown must be hidden and the Iqama must start immediately after adhan and duaa, in the current vers i force iqama to 3 minutes when it's under 3

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#554]

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
Salam Brother.
Could explain this issue a little bit?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes try to put 0 min in iqama of any prayer and observe teh behaviour when iqama starts.
Here is the logic I implemented in js https://github.com/mawaqit/backend/blob/c46adfaeb467ec4da9fee2eebd0690fcf8164fc6/src/AppBundle/Resources/public/prayer-times/js/prayer.js#L163
I force iqama to 2 min if it's lower then or equal to 2 min, because even if the admin chooses 0 min for example we need minimum time for adhan...etc

**Comment by ibrahim-zehhaf-mawaqit** [comment]
- [ ] Adhan signal is hidden immediately after apparition, please see here for the duration logic
https://github.com/mawaqit/backend/blob/c46adfaeb467ec4da9fee2eebd0690fcf8164fc6/src/AppBundle/Resources/public/prayer-times/js/prayer.js#L527
- [ ] Duaa after athan sound is played for mosque, it should be only for the other types

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit Any updates about this issue
