### ISSUE TITLE
Bip, adhan, and duaa after adhan sounds not work when offline

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#606]
All the mp3 sounds must be stored locally in the app and not fetched from the internet

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
Because users/mosques will use only one single adhan 
instead of downloading all the adhans and increasing the APK size 
I used the online values and cached them locally for future usage 
so the user will only download this adhan single time 

 What do you prefer  
- keeping it as it is 
  - and precache the adhan on the (onboarding, user changes his mosque)
- save all voices in the assets

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes but the user can change the athan from the admin console.

I suggest to precache the chosen athan on the first start and for each start you check if it's precached and download it .
the user can clear the cache, he will lose the athan file.

The pb is when the user change the adhan and the app is already opened, how you  precache the adhan ?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
OK 👍
