### ISSUE TITLE
Fix crashes

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#679]
![image](https://user-images.githubusercontent.com/97339607/227450941-30bcf3df-4dfe-460a-91c0-2585276222af.png)

**Comment by ismaelAbogabal** [comment]
This is a build issue.
Due to this [article](https://medium.com/codechai/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd)
The main issue is that flutter isn't adding libflutter.so the library in the output apk 
And we should remove arm64-v8a to solve this issue 

![image](https://user-images.githubusercontent.com/63953869/227546674-1cfadecf-955c-4394-872b-47814567619e.png)

I am not fully aware of this topic 
@ibrahim-zehhaf-mawaqit So what do you think we should do in such a situations

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit This is a [flutter engine issue](https://github.com/flutter/flutter/issues/73943) 
We may have a flutter update that fixes this issue in the future 

I tried to build only for X32 architectures(armeabi-v7a) but it didn't work as now Google requires to have 
So The solution that comes to mind now is splitting the output APKs per API so we will have (armeabi-v7a, arm64-v8a)

Is this possible for our com.kanout.app to have multiple APKs instead of the regular app bundle?
