### ISSUE TITLE
Athkar translation 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#692]
We must have 2 version of athkar after salat,
Arabic and phonetic on the same screen 

for all languages except arabic, only arabic text must be displayed 

Verse and surate must be in arabic only no phonetic translation

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
What I did understand is that the logic is in the azkar screen

1. We always show the Arabic text regardless of the app locale or zikr item type 
2. We show the translated item if 
    1. app locale isn't Arabic 
    2. Zikr item isn't Quran aya

If this is right 
This can be accomplished easily from the crowdin by 
1. translate the item that we want to be available in dual languages 
2. keep the Quran ayat items not translated 

This is the current logic in the screen 
1. if the item is translated into English and other languages it will show in dual-language mode 
2. otherwise it will show only in Arabic

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal yes this is the logic if you can do it on crowdin, let's go thanks

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit done it from crowdin 
But for some reason, crowdin isn't syncing the branch and not doing a pull requests.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal Now crowdin is syncing, could you please fix

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit The azkar list is done but there is no pull created by crowdin
