### ISSUE TITLE
Use the cached value in case of backend response with error 

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#703]
### Issue 
We are checking the backend each 1min to check if there are any new data 
there might be an error response in case the server is down for a minute I got 502

I think we should use the cached (mosque, times, config) but not the (weather) in such a situation 

But there is a case where we should show the error 
when the mosque is been disabled which is 404 response code

So if the response status code is 404 we will show the error UI 
otherwise, we will use the cached value normally 

@ibrahim-zehhaf-mawaqit 
If there are any status codes that the backend return that should show the error UI please let me know 
otherwise, I can change the ApiInterceptor  to throw an error only if the response is 404

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes this is OK, show error UI for 404 status only.
For all other error status use the cache (do nothing)

200 : update the data
404 : Show UI error (mosque not found or suspended by MAWAQIT)
304 : do nothing (data not modified since last update)
5XX: do nothing, keep the current data
Other XXX : do nothing, keep the current data

Did you apply this requirement ?
![image](https://user-images.githubusercontent.com/97339607/227795116-cf867aa5-3292-40e6-8f22-cb2c64894061.png)

**Comment by ismaelAbogabal** [comment]
Yes 
The last modification is saved in the cache when I do any requests in the future I send this value with the request 

if the response is 304 I use the cached value
