### ISSUE TITLE
MAWAQIT for TV (Beta) cannot be installed on some devices (Xiaomi for example)

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#744]
Could you please double check the AndroidManifest to make sure that the build on MAWAQIT For TV (Beta) to make sure there's no LeanBack requirements ?

The App should be installed on any box on the market, and any tablet. With or without Leanback.
Baraka'Allah fik.

Image below reported by @ibrahim-zehhaf-mawaqit on Discord.
![image](https://user-images.githubusercontent.com/33727630/229796879-af1fd08f-dc2a-4dc9-9e93-2dbbab9c009f.png)

**Comment by ismaelAbogabal** [comment]
For some reason, google didn't push the internal testing version of the into the internal testers 

This version which has the fix for this issue is in the internal testing track 
Please promote it into production.


I check the feature list of the app on the internal testing and it doesn't have the leanback feature

**Comment by omar-cherif** [comment]
@ismaelAbogabal I thought that it was the case. Could you please prepare a 1.1.46 build with com.kanout.mawaqit and leanback true please? Add the generated .aab bundle in the internal testing in MAWAQIT Ramadan 2023 app.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
leanback is ok on the v1.1.47 which in production in MAWAQIT Ramadan 2023 app.
You see this in features and not in permission @ismaelAbogabal 

![image](https://user-images.githubusercontent.com/97339607/229884093-e3471489-2d05-476c-90f6-81d882480e7c.png)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
For the v1.1.50 MAWAQIT for TV app, it's in internal test yes, and we can't promote it to production because it still in testing and has some bugs

![image](https://user-images.githubusercontent.com/97339607/229884922-961c7faf-21c5-4a2d-9cd8-184d81d787db.png)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit There is a slight bug here 
I checked the internal testers list and I am on this list with my two accounts (personal, mawaqit)
But in the app screen on google play, I am getting the production version of the app 

I think you too getting the production one 
Do you have any clue about this bug?

**Comment by ismaelAbogabal** [comment]
Thanks, I checked it and it can be installed on all my devices.

This issue is done, right?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Keep it open until I return to home and check on my box

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal unfortunately the app still not available when i search on Google Play from my mi box 3 
Only the mobile app bundle is found 

![IMG_9788](https://user-images.githubusercontent.com/97339607/232928689-7466a3c9-19d8-44ec-82d6-82d073965c5e.jpeg)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
But when i enter in MAWAQIT - Ramadan 2023 app and go to the bottom of the screen i find MAWAQIT for TV app

![IMG_9789](https://user-images.githubusercontent.com/97339607/232929457-6e18366e-bb6e-494a-bf45-3fcb807683ab.jpeg)
![IMG_9790](https://user-images.githubusercontent.com/97339607/232929465-22d0d3b9-43c0-4ebe-a028-497788cf8ec3.jpeg)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit Yes 
I tested on Mi BOX, Chromcast 4

This issue now isn't related to leanback feature 
But I don't know what is causing this as the app is clearly installable on these devices.

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit It seems that our Mawaqit for TV app isn't indexed in the Google search engine that's why it's not showing up on the search results ['try to search for it in Google'  ](https://www.google.com/search?q=mawaqit+for+tv+site%3Aplay.google.com&sxsrf=APwXEdevux0epsH9NpEK7gVtlk5e5a6K5A%3A1683192694055&ei=dntTZOPuAqfO7_UPgJe1iA0&ved=0ahUKEwjjgfi0rdv-AhUn57sIHYBLDdEQ4dUDCA8&uact=5&oq=mawaqit+for+tv+site%3Aplay.google.com&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzoHCCMQsAMQJzoKCAAQRxDWBBCwAzoECCMQJzoGCAAQFhAeOggIABCKBRCGAzoICCEQoAEQiwM6BQghEKABSgQIQRgAUC9Y5j9gnUFoAnABeACAAcoBiAHFG5IBBjAuMjEuMZgBAKABAcgBCLgBAsABAQ&sclient=gws-wiz-serp)

# Solutions 
1. request google to index it 
2. add more links inside our website that refer to the 'Mawaqit for TV' app on google play 
3. update the description with more text to increase its ranking 

We can do all the solutions in parallel as they will increase our ranking on Google

**Comment by ismaelAbogabal** [comment]
MAWAQIT offers a new way to track and manage prayer schedules. Indeed, we offer an end-to-end system that provides mosque managers with online tools available 24/24h allowing them to manage the schedules, the news of the mosque and many other features. Worshipers, on the other hand, benefit from a mobile application that allows them to consult the exact and not approximate schedules of their favourite mosque, as well as the news and other features such as mosque search by geolocation. We have made reliability and quality our core values. Our ambition is clear: to build the best service for our mosques through technology and design. Every mosque added to our system goes through a thorough moderation. We suspend any mosque that does not comply with our rules in order to preserve a reliable service for the community.

Our salah mawaqit TV application is designed to enhance your prayer experience and help you stay connected to your faith. Here are the key features of our app:

1. Prayer Time: Our app provides precise prayer timings for Fajr, Zuhr, Asr, Maghrib, and Isha based on your location. Never miss a prayer again with our easy-to-use interface and customizable settings.

2. Accurate Adhan Time: Our app offers accurate Adhan timings for each prayer, so you can hear the call to prayer and start your salah on time. With our app, you can trust that you're always in sync with the local masjid.

3. Iqama Time and Countdown: Our app includes iqama timings for each prayer, along with a countdown timer to let you know how much time is left until the prayer starts. This feature helps you plan your prayer routine and ensures that you're always prepared for salah.

4. After Salah Azkar: Our app provides a range of after salah Azkar, so you can keep the remembrance of Allah fresh in your mind after completing your prayer. With our app, you'll have access to a variety of supplications and duaa to recite after salah.

5. After Adhan Duaa: Our app includes a collection of after-adhan Duaa, so you can supplicate to Allah after hearing the call to prayer. This feature helps you connect with your faith and deepen your spiritual experience.

6. Show Azkar and Ayat All Day: Our app offers a feature that allows you to display Azkar and Ayat throughout the day. This feature is especially useful if you want to maintain a constant connection with your faith and keep your mind focused on Allah.

7. Show Custom Images and Videos: With our app, you can choose to display custom images and videos of your choice during prayer times or throughout the day. This feature enables you to personalize your prayer experience and make it unique to your preferences.

In summary, our salah mawaqit TV application offers a comprehensive and customizable prayer experience. With accurate prayer timings, adhan timings, iqama timings, after salah Azkar, after adhan Duas, and a range of customizable features such as displaying Azkarand ayat or custom images and videos, our app is designed to meet all of your prayer needs and elevate your spiritual experience. Download now and experience the convenience of having salah mawaqit at your fingertips!

Get accurate and reliable salah mawaqit timings on your TV screen with our innovative application. Our app provides precise timings for Fajr, Zuhr, Asr, Maghrib, and Isha prayers based on your location. Never miss a prayer again with our easy-to-use interface and customizable settings. With our salah mawaqit TV application, you can stay connected to your faith and maintain your daily prayer routine with ease. Download now and experience the convenience of having salah mawaqit at your fingertips!

Stay on top of your daily prayers with our salah mawaqit TV application. Our app offers comprehensive and reliable prayer timings for your location, so you never have to worry about missing a prayer again. With easy-to-use navigation and customizable settings, our app is designed to enhance your home Tv and help you stay connected to your faith. Mawaqit for TV is your perfect companion. Download now and take the first step towards a more fulfilling prayer routine

More details about our installation process will be found here https://help.mawaqit.net/en/articles/6086131-opening-mawaqit-display-app

**Comment by ibrahim-zehhaf-mawaqit** [comment]
It's not normal, yhe name of the app is MAWAQIT For TV and when you search for the keyword MAWAQIT, it's not available in the result, but on the X98Q box it is

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal could please contact google to kwnom more about this issue, and request to index it as you suggest

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal 🆙

**Comment by ismaelAbogabal** [comment]
They don't have a support email. I send my email to their [support webpage. ](https://support.google.com/googleplay/android-developer/gethelp?sjid=1676471249797042962-EU)

> Dear Google Team,
> 
> I am reaching out to you today regarding an issue that our team has encountered with our Android TV application, Mawaqit for TV. Despite being uploaded to the Google Play Store, our app is not appearing in Google search results. We have attempted to request a crawl of the app using Google Search Console, but unfortunately, we are unable to do so as we do not have ownership of the google store domain.
 > 
> Therefore, we kindly request your assistance in triggering a manual crawl request for our application or informing us via email if there are any issues with our app preventing it from appearing in search results. This will enable us to address any concerns and ensure the application is accessible to the intended audience.Thank you for your time and attention to this matter.
> 
> Sincerely,
> 
> Ismael

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
Google Play support respond that we need to fill in the screenshots of Android Tv and enable the android tv form factor.

![image](https://github.com/mawaqit/android-tv-app/assets/63953869/6a7556e6-38d2-4e38-8eec-9944cc2c7fb2)
 I don't have the full-definition screenshots.
 So could please refer it to the UI team?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Thanks @ismaelAbogabal 
But I don't have this screen in the main store listing
Could you please tel me when you have this upload area

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit They asked to enable the android tv form factor in their response 

![image](https://github.com/mawaqit/android-tv-app/assets/63953869/8c75dad5-20dc-4123-b280-b97c275d4932)


![image](https://github.com/mawaqit/android-tv-app/assets/63953869/ba19c6f6-0ccb-4688-8fed-87aa5b9abe5c)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal Android TV enabled from factor but unfortunately this update has been rejected, we need fix the Dpad control, I forwarded the email to you

![image](https://github.com/mawaqit/android-tv-app/assets/97339607/63b7d7cc-1a96-42a6-a5de-968b9c6a36bc)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
Strange 

Our app is working fine with DPad we had no issue with 
I checked the play console fount that app is publish 

![image](https://github.com/mawaqit/android-tv-app/assets/63953869/a40885cc-e241-48dc-8b54-fe1651dc7528)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes the app is published but the option Android TV form factors has been rejected
![image](https://github.com/mawaqit/android-tv-app/assets/97339607/83957869-8721-4c5b-8d5d-e0fe13344b12)

Please make the menu appear when the user clic on each Dpad buttons (top, bottom and select)

![image](https://github.com/mawaqit/android-tv-app/assets/97339607/b1e4a892-e942-488d-b387-718da40f1704)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit  Google team responded with an email that I didn't fully understand at first.
After searching I found out that they are complaining about these buttons 

![image](https://github.com/mawaqit/android-tv-app/assets/63953869/c1948d0c-572a-4fff-af52-b28788a623ec)


The four screens 
- Network status 
- Privacy policy 
- Terms of service 
- Installation guide 

doesn't have proper focus movement it only has the ability to scroll based on the pad keys UP, Down this is implemented using a dart 


Will continue my research if it's possible to handle the focus properly inside the Webview. or build a javascript bridge to move the remote action into the Webview.

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit Brother these four screens can re-implement them as a dart code. to skip this conflict. So we have the app 100% pure dart code.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
I suggest deleting them now to speed up the resolution of the pb
All these informations are available on our website
