### ISSUE TITLE
Wrong color of jumua highlight

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#799]
![IMG_9976](https://github.com/mawaqit/android-tv-app/assets/97339607/dd110884-0797-4d1a-9010-65809219ca4b)

I m on autumn theme

check also the others themes and eid highlight

**Comment by ismaelAbogabal** [comment]
The Jumuaa, Eid, Shuruk, and Salah items are built using the same widget 
The color difference comes from the background. because of the opacity. 

But I noticed that there is also a difference in color in the logo. 
The logo on the screen is showing in blue color but the logo should look like this. ![image](https://github.com/mawaqit/android-tv-app/assets/63953869/6a084629-dc30-4a12-98e4-8bdac17231fc)

My solution for this is to reduce the opacity of the color to reduce the effect of the background.

Please check if any colour filter is coming from the screen settings.
