### ISSUE TITLE
Iqama of tomorrow is not loaded after isha

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#813]
Dear Mawaqit developers
<br>AssalamuAllaikum

I would like to draw your attention to an important issue.

When people complete their Isha prayer they look at Mawaqit screen to know the time for Fajr prayer. But at that time the Fajr Iqama time being shown is for the past Fajr. The next morning Fajr Iqama time is shown only after midnight. This does not help.

I suggest that every prayer Iqama time should update few minutes after that prayer to show the next day prayer Iqama time. This would help people being well informed about the prayer times. 

Jazakallahu Khairan 

Kind regards
<br>Dr Abdul Mughees
<br>Lucan Islamic Centre of Ireland

**Link:** [Conversation with Lucan Islamic Community Centre](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900161595)

**Customer:** [Lucan Islamic Community Centre](https://app.intercom.com/a/apps/piphhhai/users/63f2b3094081280187c340cc/all-conversations)
**Customer ID:** whatsapp:9fa52622-3fb6-48aa-a186-7fd7d11db2bc
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900161595) when this issue is closed.

**Comment by Masum2004** [comment]
Assalamu Allaikum

We started using Mawaqit last month, while we love most of the features MAWAQIT offers, this was something of a real issue. 

In order to mitigate this we started using Flash Messages day before the Jamah/Iqama time change (we use fixed time for iqama).

I was thinking to raise this but looks like it’s already in the pipeline, Alhamdulillah.

it will be good to change the Iqama time after a fixed time (I.e. 10 mins) or based on variable ‘estimated duration of each prayer’ from the configuration. That way when the screen turns back on (if it’s set to stay off during Jamah) next iqama time will be displayed. 

جزاك اللهُ خيراً‎

**Comment by Masum2004** [comment]
Assalamu-alaikum Brother Ibrahim

Hope this message finds you in good health and Imaan.

I’m messaging regarding the issue (#813), raised by another mosque admin (Dr Abdul Mughees of Lucan Islamic Centre of Ireland), which I responded/supported to as well.

Did you address the issue raised on 813, as it was closed?

We (Aberfeldy Masjid, ID 16071) are still dealing with this same issue and it will be really helpful for our community if you could have a second look.

Our Iqama times are on SET TIME (except Magrib) rather than +10, +15 etc. (example: Fazr is on 3:45 whole week and then 4:00am from Saturday next week). This is the case for majority of mosques in UK, as far as my knowledge goes.

When the Iqama time changes (our time usually changes on Saturdays but not every Saturday), so day before the time change (usually Friday for us) throughout the day/evening,  Iqama time displayed on the screen is/are invalid for the next day (for those that are changing).

For example, our Fazr prayer time changed from (today/tonight) 3:30am to 3:45am. Due to the time update happening at the midnight, Fazr time was showing 3:30am throughout the day, even after Isha prayer / 11:00pm (please see the screenshot).

[Image.jpeg]

Please see my previous comment on GitHub: https://github.com/mawaqit/android-tv-app/issues/813#issuecomment-1575248398

It would be great to have the prayer time for the next day is displayed after a fixed/set amount of time of the current day (I.e. - Fazr Prayer time changes on the display after Shuruq).

We look forward to your response and co-operation.

جزاك اللهُ خيراً‎

Kind regards,
Masum Ahmed
________________________________

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal can you check please
You fixed it but it  is back

i can reproduce it

**Comment by Masum2004** [comment]
Thank you Ibrahim & @ismaelAbogaba<https://github.com/ismaelAbogabal> for looking into this. Much appreciated.

In addition to the Fazr, it would be great to have other Salah time also refreshed/changed after a specified amount of time so that the prayer times on the Mawaqit displays are always correct. This is the only drawback I realised over the Manual system we were using since we changed to Mawaqit. Hopefully you will assist us to overcome this.

Fazr is the top priority as it displays incorrect time throughout the whole day. If this can be addressed first that will be a great help.

Next priority would be Asr as often the time between Asr and midnight can be up to 10 hours (depending on location).

Magrib can be changed after 30 mins or at the start of Isha. If it's too much to ask, then can be left to change at midnight.

Isha is not a big issue as it's the last salah of the day and can change at the midnight without much of an issue, as I know it can cause issues like double iqama for the same salah, in situation where the prayer time moves forward next day (when the day gets longer) and the time is changed before the new time, causing the iqama to trigger again, unless additional logics are applied to avoid this.

The above will really help a lot of Masjids like ours and across the globe with set iqama time for each salah (E.g. - Asr iqama at 7:00pm, then 7:15pm and 7:30 so on....) for certain number of days, instead of iqama time is based on the start time.

I am sure you will find out the best logic to address this but to start with, if Fazr can be refreshed/changed at the time of Shuruq, it will be safest to say that there will be no chance of getting 2 iqama alerts for the same day. Even though I believe around 61 mins after iqama time will be more than enough to avoid having 2 Fazr iqamas same day. As 61 mins allows up to an hour of iqama time forwarding next day.

Thank you so much again for all your hard work, may Allah (SWT) reward you abundantly.

Please let me know if you want me to test anything from my end when the time comes.

Kind regards,

Masum Ahmed

________________________________

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
I tested tomorrow's iqama in MOSQUE ID: 1
 And it worked and showed the tomorrow Iqama times after the Isha screens 

https://github.com/mawaqit/android-tv-app/assets/63953869/bb274e2d-a679-49e9-8d90-d829983279e2

**Comment by Masum2004** [comment]
@ismaelAbogabal 
Thanks for the update. Would it not be more sensible to change it after the Fazr salah finished (say from the time of sunrise) as the time displayed on the screen during the day is not correct for the upcoming Fazr?

Is it too complicated than doing it after Isha?

**Comment by Masum2004** [comment]
@ismaelAbogabal @ibrahim-zehhaf-mawaqit @

Further to my previous message, I just want to reiterate that it’s critical for the mosques that have a fixed time for Iqama like 4:00am, which changes to 4:15am then 4:30am and so on. It’s a matter of someone missing the salah for not knowing the time change, due to incorrect time displayed throughout the day. 

Doing it after Isha means throughout the day the incorrect time is displayed and if someone doesn’t attend Isha for whatever reason or doesn’t look at the screen after Isha then they won’t know.

In a manual system every masjid change their time after the Salah, I understand there may be the need for more work to avoid double iqama for half of the year, if the time is changed at a time before the time it’s changed to for the following day. Hence I believe changing at Sunrise is safe option, as no Fazr iqama can be after sunrise.

I have explained this in detail in my previous messages at least twice but you seem to have missed it completely.

@fkanout @AppropriateEagle - Do you agree with the above, please let MAWAQIT know.

جزاك اللهُ خيراً‎

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Salam alaykum brother @Masum2004 
We didn't miss your message, thank you so much for your comments and using MAWAQIT.
We decided to keep changing times and iqama after isha 

If the mussali misses the isha at mosque he can check the tomorrow times on the mobile app before coming to the mosque

**Comment by Masum2004** [comment]
> Salam alaykum brother @Masum2004 We didn't miss your message, thank you so much for your comments and using MAWAQIT. We decided to keep changing times and iqama after isha
> 
> If the mussali misses the isha at mosque he can check the tomorrow times on the mobile app before coming to the mosque

وَعَلَيْكُمُ السَّلاَمُ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ 

I can see that you have decided to go with changing it after Isha. It would be good to know what was the reason behind not changing it earlier than Isha time. 

We have many elderly worshippers who either don’t have a phone or don’t use a smartphone, for them the mosque display is everything. I wouldn’t have wasted my time and energy on explaining this over and over if it was not an issue. 

You say, you have not ignored my comments/concerns but without a valid answer it clearly indicates that you have divided to completely ignore me. 

Allah knows best, may Allah (سُبْحَانَهُ وَ تَعَالَى) accept our intentions.
