### ISSUE TITLE
The countdown for shuruq was wrong today after fajr

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#886]
After salat of fajr the countdown showed 1 min instead of 1 hour and started showing the countdown of duhr

**Comment by ibrahim-zehhaf-mawaqit** [comment]
No issue for me at home
The issue is on my mosque id 1847

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit The issue is that we arent applying summer time to shuruk.

### Issue
I checked The mosque 1847 in postman and found out that.
Fajr time: 05:53 
Iqama After: +10
Salah time: +9

Shuruk time: 06:09

Which means the fajr invocation ends after shuruk time 

### Solve
May be we can fix it by doing the sammer time also for the shuruk time

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Wa already apply summer time for shuruq, and FYI I use the same calendar at home ID 116, I don't have this pb 

![image](https://github.com/mawaqit/android-tv-app/assets/97339607/92808cad-7b06-4d4f-a7a3-fb464437241c)

![image](https://github.com/mawaqit/android-tv-app/assets/97339607/35f0d410-e9f9-4b2a-89dd-6662e223312a)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit That seems to be the issue 
Because we were using the shuruk directly from the response not from the calendar 


Quick question: will the second item on the day times will be the shuruk? in all mosques? 

![image](https://github.com/mawaqit/android-tv-app/assets/63953869/94acb9a6-9249-4be1-a802-6adf2146c876)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes use only calendar for shuruq and prayer times
